// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: decks.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addFlashcardToDeck = `-- name: AddFlashcardToDeck :execrows
INSERT INTO deck_flashcards (deck_id, flashcard_id)
SELECT d.id, f.id
FROM decks d
         INNER JOIN flashcards f ON f.user_id = d.user_id
WHERE d.id = $1
  AND f.id = $2
  AND d.user_id = $3
`

type AddFlashcardToDeckParams struct {
	ID     pgtype.UUID `json:"id"`
	ID_2   pgtype.UUID `json:"id_2"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) AddFlashcardToDeck(ctx context.Context, arg AddFlashcardToDeckParams) (int64, error) {
	result, err := q.db.Exec(ctx, addFlashcardToDeck, arg.ID, arg.ID_2, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createDeck = `-- name: CreateDeck :one
INSERT INTO decks(user_id, name, description)
VALUES ($1, $2, $3)
RETURNING id, user_id, name, description, created_at, updated_at
`

type CreateDeckParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) CreateDeck(ctx context.Context, arg CreateDeckParams) (Deck, error) {
	row := q.db.QueryRow(ctx, createDeck, arg.UserID, arg.Name, arg.Description)
	var i Deck
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDeck = `-- name: DeleteDeck :execrows
DELETE
FROM decks
WHERE id = $1
  AND user_id = $2
`

type DeleteDeckParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteDeck(ctx context.Context, arg DeleteDeckParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDeck, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDeck = `-- name: GetDeck :one
SELECT d.id, d.user_id, d.name, d.description, d.created_at, d.updated_at
FROM decks d
WHERE d.id = $1
  AND d.user_id = $2
`

type GetDeckParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetDeck(ctx context.Context, arg GetDeckParams) (Deck, error) {
	row := q.db.QueryRow(ctx, getDeck, arg.ID, arg.UserID)
	var i Deck
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDecks = `-- name: ListDecks :many
SELECT d.id, d.user_id, d.name, d.description, d.created_at, d.updated_at
FROM decks d
WHERE d.user_id = $1
ORDER BY d.created_at DESC
`

func (q *Queries) ListDecks(ctx context.Context, userID pgtype.UUID) ([]Deck, error) {
	rows, err := q.db.Query(ctx, listDecks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deck
	for rows.Next() {
		var i Deck
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeFlashcardFromDeck = `-- name: RemoveFlashcardFromDeck :execrows
DELETE
FROM deck_flashcards AS df
    USING decks d
WHERE df.deck_id = d.id
  AND df.deck_id = $1
  AND df.flashcard_id = $2
  AND d.user_id = $3
`

type RemoveFlashcardFromDeckParams struct {
	DeckID      pgtype.UUID `json:"deck_id"`
	FlashcardID pgtype.UUID `json:"flashcard_id"`
	UserID      pgtype.UUID `json:"user_id"`
}

func (q *Queries) RemoveFlashcardFromDeck(ctx context.Context, arg RemoveFlashcardFromDeckParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeFlashcardFromDeck, arg.DeckID, arg.FlashcardID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateDeck = `-- name: UpdateDeck :one
UPDATE decks
SET name        = $3,
    description = $4,
    updated_at  = NOW()
WHERE id = $1
  AND user_id = $2
RETURNING id, user_id, name, description, created_at, updated_at
`

type UpdateDeckParams struct {
	ID          pgtype.UUID `json:"id"`
	UserID      pgtype.UUID `json:"user_id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) UpdateDeck(ctx context.Context, arg UpdateDeckParams) (Deck, error) {
	row := q.db.QueryRow(ctx, updateDeck,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Description,
	)
	var i Deck
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
