// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: flashcards.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFlashcard = `-- name: CreateFlashcard :one
INSERT INTO flashcards(user_id, front, back, example)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, front, back, example, created_at, updated_at
`

type CreateFlashcardParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	Front   string      `json:"front"`
	Back    string      `json:"back"`
	Example pgtype.Text `json:"example"`
}

func (q *Queries) CreateFlashcard(ctx context.Context, arg CreateFlashcardParams) (Flashcard, error) {
	row := q.db.QueryRow(ctx, createFlashcard,
		arg.UserID,
		arg.Front,
		arg.Back,
		arg.Example,
	)
	var i Flashcard
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Front,
		&i.Back,
		&i.Example,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFlashcard = `-- name: DeleteFlashcard :execrows
DELETE
FROM flashcards
WHERE id = $1
  AND user_id = $2
`

type DeleteFlashcardParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteFlashcard(ctx context.Context, arg DeleteFlashcardParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFlashcard, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listFlashcards = `-- name: ListFlashcards :many
SELECT f.id, f.front, f.back, f.example, f.created_at, f.updated_at
FROM flashcards AS f
WHERE f.user_id = $1
  AND ($2::uuid IS NULL OR f.id < $2)
ORDER BY f.id DESC
LIMIT $3
`

type ListFlashcardsParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	Cursor   pgtype.UUID `json:"cursor"`
	PageSize int32       `json:"page_size"`
}

type ListFlashcardsRow struct {
	ID        pgtype.UUID        `json:"id"`
	Front     string             `json:"front"`
	Back      string             `json:"back"`
	Example   pgtype.Text        `json:"example"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// Keyset pagination, newest first. Flashcard ids are uuidv7, whose leading bits
// are a timestamp, so ordering by id is chronological and the last id on a page
// is a stable cursor: unlike OFFSET it can't skip or repeat rows when cards are
// inserted mid-listing, and it never scans the rows it skips. Pass a NULL cursor
// for the first page.
func (q *Queries) ListFlashcards(ctx context.Context, arg ListFlashcardsParams) ([]ListFlashcardsRow, error) {
	rows, err := q.db.Query(ctx, listFlashcards, arg.UserID, arg.Cursor, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFlashcardsRow
	for rows.Next() {
		var i ListFlashcardsRow
		if err := rows.Scan(
			&i.ID,
			&i.Front,
			&i.Back,
			&i.Example,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFlashcard = `-- name: UpdateFlashcard :one
UPDATE flashcards
SET front      = $1,
    back       = $2,
    example    = $3,
    updated_at = NOW()
WHERE id = $4
  AND user_id = $5
RETURNING id, user_id, front, back, example, created_at, updated_at
`

type UpdateFlashcardParams struct {
	Front   string      `json:"front"`
	Back    string      `json:"back"`
	Example pgtype.Text `json:"example"`
	ID      pgtype.UUID `json:"id"`
	UserID  pgtype.UUID `json:"user_id"`
}

func (q *Queries) UpdateFlashcard(ctx context.Context, arg UpdateFlashcardParams) (Flashcard, error) {
	row := q.db.QueryRow(ctx, updateFlashcard,
		arg.Front,
		arg.Back,
		arg.Example,
		arg.ID,
		arg.UserID,
	)
	var i Flashcard
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Front,
		&i.Back,
		&i.Example,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
