// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Deck struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type DeckFlashcard struct {
	DeckID      pgtype.UUID        `json:"deck_id"`
	FlashcardID pgtype.UUID        `json:"flashcard_id"`
	Position    pgtype.Int4        `json:"position"`
	AddedAt     pgtype.Timestamptz `json:"added_at"`
}

type Flashcard struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Front     string             `json:"front"`
	Back      string             `json:"back"`
	Example   pgtype.Text        `json:"example"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type FlashcardReview struct {
	ID          pgtype.UUID `json:"id"`
	FlashcardID pgtype.UUID `json:"flashcard_id"`
	UserID      pgtype.UUID `json:"user_id"`
	// 1=again, 2=hard, 3=good, 4=easy
	Rating     int16              `json:"rating"`
	DurationMs pgtype.Int4        `json:"duration_ms"`
	ReviewedAt pgtype.Timestamptz `json:"reviewed_at"`
}

type Session struct {
	Token  string             `json:"token"`
	Data   []byte             `json:"data"`
	Expiry pgtype.Timestamptz `json:"expiry"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	IsActive     bool               `json:"is_active"`
	IsVerified   bool               `json:"is_verified"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	LastLoginAt  pgtype.Timestamptz `json:"last_login_at"`
}
